name: Release

on:
  push:
    tags: [ "v*.*.*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        if: endsWith(github.ref, 'main')
        uses: softprops/action-gh-release@v2