name: Release

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: get-branch-name
        run: |
          BRANCH_NAME=$(git branch --contains ${{ github.event.after }} | sed -n 1p | awk '{print $2}')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV    

      - name: Release
        if: env.BRANCH_NAME == 'main'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ contains(env.BRANCH_NAME, '-rc') }}